version: "3.0"
services:
  dockerapp:
    build: .
    ports:
      - "5000:5000"
    networks:
      - my_network
    depends_on:
      - redis
  redis:
    image: redis:3.2.0
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
